Repository FE8-team5/ESCape, pull requests merged in 2024-11, with the labels that each got.

#165 Refactor(김세환): 프로덕트페이지 조건부랜더링을 ts-pattern을 이용해 코드 중복 제거
  .eslintcache
  src/components/product/ProductMain.tsx
  src/components/productDetail/detail/ProductDetailSection.tsx
Labels: refector

#163 Feat(김종화) : API 정리 및 좋아요 기능 구현
  next.config.mjs
  public/icons/like_icon.svg
  public/icons/unlike_icon.svg
  src/components/board/BoardCard.tsx
  src/components/board/BoardPatchModal.tsx
  src/components/board/BoardSection.tsx
  src/components/board/CommentDeleteModal.tsx
  src/components/board/DetailContentSection.tsx
  src/libs/axios/addboard/postArticles.ts
  src/libs/axios/board/deleteArticles.ts
  src/libs/axios/board/deleteComments.ts
  src/libs/axios/board/deleteLike.ts
  src/libs/axios/board/getArticleDetail.ts
  src/libs/axios/board/getArticleDetailComments.ts
  src/libs/axios/board/getArticles.ts
  src/libs/axios/board/getArticlesByLike.ts
  src/libs/axios/board/patchArticles.ts
  src/libs/axios/board/patchComments.ts
  src/libs/axios/board/patchUsers.ts
  src/libs/axios/board/postComments.ts
  src/libs/axios/board/postImage.ts
  src/libs/axios/board/postLike.ts
  src/libs/axios/board/postUsers.ts
  src/pages/board/[id].tsx
  src/pages/board/index.tsx
Labels: feat, refector

#164 Feat(서지훈) : QA 사항 수정(4차)
  src/components/productDetail/ConfirmModal.tsx
  src/components/productDetail/ReviewModal.tsx
  src/components/productDetail/detail/FeatureTag.tsx
  src/components/productDetail/detail/ProductDetailSection.tsx
  src/components/productDetail/review/ProductReviewSection.tsx
  src/components/productDetail/review/SortDropdown.tsx
  src/contexts/ToasterProvider.tsx
  src/dtos/ProductDto.ts
  src/hooks/useInfiniteReviews.tsx
  src/libs/axios/product/reviewApi.ts
Labels: feat, fix

#172 Fix(김종화): null 예외 처리 추가로 인한 버그 개선
  src/components/board/BoardCard.tsx
  src/components/board/CommentCard.tsx
  src/pages/board/index.tsx
Labels: fix

#182 fix(서지훈):toast 위치 변경
  .eslintcache
  src/contexts/ToasterProvider.tsx
  src/libs/axios/product/category.ts
Labels: fix

#183 Fix(나윤주): 리다이렉트 수정
  src/components/auth/GoogleOauthButton.tsx
  src/components/auth/KakaoOauthButton.tsx
  src/components/auth/NicknamePage.tsx
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
Labels: fix

#184 Fix(서지훈):review 부분 수정
  src/components/productDetail/review/ProductReviewSection.tsx
Labels: design, fix

#185 Fix(오정민): 마이페이지 테마 리스트가 필터에 맞게 랜더링 되도록 수정
  src/components/mypage/FollowUserList.tsx
  src/components/mypage/ProductCardList.tsx
  src/components/mypage/Profile.tsx
Labels: design, fix

#186 Fix(나윤주): 0auth/로그인 기능 수정
  .eslintcache
  src/components/auth/GoogleOauthButton.tsx
  src/components/auth/KakaoOauthButton.tsx
  src/components/auth/NicknamePage.tsx
  src/contexts/AuthProvider.tsx
  src/libs/axios/axiosInstance.ts
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
  src/pages/signin/index.tsx
Labels: fix
