Repository FE8-team5/ESCape, pull requests merged in 2024-10, with the labels that each got.

#19 Feat(김세환): 공용 버튼 컴포넌트 구현
  package-lock.json
  package.json
  src/components/@shared/button/PrimaryButton.tsx
  src/components/@shared/button/SecondaryButton.tsx
  src/components/@shared/button/TertiaryButton.tsx
  src/pages/product/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: feat

#26 Design(김종화): 자유게시판 기본 레이아웃 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  package-lock.json
  package.json
  public/icons/heart_icon.svg
  public/icons/kebab_icon.svg
  public/icons/medal_icon.svg
  public/icons/profile_icon.svg
  public/icons/search_icon.svg
  public/icons/toggle_icon.svg
  src/components/@shared/DropDown.tsx
  src/components/board/AddBoardButton.tsx
  src/components/board/BestBoardCard.tsx
  src/components/board/BestBoardSection.tsx
  src/components/board/BoardCard.tsx
  src/components/board/BoardSection.tsx
  src/components/board/SearchSection.tsx
  src/dtos/ArticleCommentDto.ts
  src/dtos/ArticleDto.ts
  src/dtos/AuthDto.ts
  src/dtos/CategoryDto.ts
  src/dtos/FollowDto.ts
  src/dtos/ImageDto.ts
  src/dtos/OauthDto.ts
  src/dtos/ProductDto.ts
  src/dtos/ReviewDto.ts
  src/dtos/UserDto.ts
  src/hooks/useToggle.ts
  src/pages/board/index.tsx
  src/utils/TimeAgo.ts
  tailwind.config.ts
Labels: design

#33 Design(나윤주): 로그인/회원가입 등록 기본 레이아웃 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  README.md
  package-lock.json
  package.json
  postcss.config.mjs
  public/icons/icon_eyes_hidden.svg
  public/icons/icon_eyes_show.svg
  public/icons/icon_google.svg
  public/icons/icon_kakao.svg
  public/images/logo.svg
  src/components/@shared/button/PrimaryButton.tsx
  src/components/@shared/button/SecondaryButton.tsx
  src/components/@shared/button/TertiaryButton.tsx
  src/dtos/ArticleCommentDto.ts
  src/dtos/ArticleDto.ts
  src/dtos/AuthDto.ts
  src/dtos/CategoryDto.ts
  src/dtos/FollowDto.ts
  src/dtos/ImageDto.ts
  src/dtos/OauthDto.ts
  src/dtos/ProductDto.ts
  src/dtos/ReviewDto.ts
  src/dtos/UserDto.ts
  src/pages/product/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: design

#36 Feat(나윤주): 회원가입 유효성 검사
  README.md
  package-lock.json
  package.json
  src/components/@shared/button/PrimaryButton.tsx
  src/pages/signup/index.tsx
Labels: feat, design

#28 Design(김종화): 자유게시판 등록 기본 레이아웃 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  package-lock.json
  package.json
  public/icons/heart_icon.svg
  public/icons/kebab_icon.svg
  public/icons/medal_icon.svg
  public/icons/plus_icon.svg
  public/icons/profile_icon.svg
  public/icons/search_icon.svg
  public/icons/toggle_icon.svg
  src/components/@shared/DropDown.tsx
  src/components/addboard/ContentSection.tsx
  src/components/addboard/HeaderSection.tsx
  src/components/board/AddBoardButton.tsx
  src/components/board/BestBoardCard.tsx
  src/components/board/BestBoardSection.tsx
  src/components/board/BoardCard.tsx
  src/components/board/BoardSection.tsx
  src/components/board/SearchSection.tsx
  src/dtos/ArticleCommentDto.ts
  src/dtos/ArticleDto.ts
  src/dtos/AuthDto.ts
  src/dtos/CategoryDto.ts
  src/dtos/FollowDto.ts
  src/dtos/ImageDto.ts
  src/dtos/OauthDto.ts
  src/dtos/ProductDto.ts
  src/dtos/ReviewDto.ts
  src/dtos/UserDto.ts
  src/hooks/useToggle.ts
  src/pages/addboard/index.tsx
  src/pages/board/index.tsx
  src/utils/TimeAgo.ts
  tailwind.config.ts
Labels: design

#34 Design(김종화): 모바일 반응형 구현
  package-lock.json
  package.json
  postcss.config.mjs
  src/components/@shared/DropDown.tsx
  src/components/@shared/button/PrimaryButton.tsx
  src/components/@shared/button/SecondaryButton.tsx
  src/components/@shared/button/TertiaryButton.tsx
  src/components/addboard/ContentSection.tsx
  src/components/addboard/HeaderSection.tsx
  src/components/board/AddBoardButton.tsx
  src/components/board/BestBoardCard.tsx
  src/components/board/BestBoardSection.tsx
  src/components/board/BoardCard.tsx
  src/components/board/BoardSection.tsx
  src/components/board/CommentCard.tsx
  src/components/board/DetailCommentSection.tsx
  src/components/board/DetailContentSection.tsx
  src/components/board/DetailPostCommentSection.tsx
  src/components/board/SearchSection.tsx
  src/pages/addboard/index.tsx
  src/pages/board/[id].tsx
  src/pages/board/index.tsx
  src/pages/product/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: design

#48 Feat(나윤주): 회원가입 페이지 api post 연결
  README.md
  src/contexts/AuthProvider.tsx
  src/dtos/AuthDto.ts
  src/dtos/OauthDto.ts
  src/hooks/(삭제)깃 인식용
  src/libs/axios/auth/auth.tsx
  src/libs/axios/axiosInstance.ts
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/utils/(삭제)깃 인식용
  src/utils/authTokenStorage.ts
Labels: feat

#43 Feat(나윤주): 로그인 유효성 검사, accesstoken 저장
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  README.md
  package-lock.json
  package.json
  postcss.config.mjs
  public/icons/icon_eyes_hidden.svg
  public/icons/icon_eyes_show.svg
  public/icons/icon_google.svg
  public/icons/icon_kakao.svg
  public/images/logo.svg
  src/components/@shared/button/PrimaryButton.tsx
  src/components/@shared/button/SecondaryButton.tsx
  src/components/@shared/button/TertiaryButton.tsx
  src/contexts/AuthProvider.tsx
  src/dtos/ArticleCommentDto.ts
  src/dtos/ArticleDto.ts
  src/dtos/AuthDto.ts
  src/dtos/CategoryDto.ts
  src/dtos/FollowDto.ts
  src/dtos/ImageDto.ts
  src/dtos/ProductDto.ts
  src/dtos/ReviewDto.ts
  src/dtos/UserDto.ts
  src/libs/axios/auth/auth.tsx
  src/libs/axios/axiosInstance.ts
  src/pages/_app.tsx
  src/pages/product/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  src/utils/authTokenStorage.ts
  tailwind.config.ts
Labels: feat

#55 Design(오정민): 마이페이지 기본 레이아웃 구현(재업로드)
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .prettierrc.json
  package-lock.json
  package.json
  postcss.config.mjs
  public/icons/comment_icon.svg
  public/icons/heart_icon.svg
  public/icons/star_icon.svg
  public/images/profile_image.png
  public/images/temp1_image.png
  public/images/temp2_image.png
  public/images/temp3_image.png
  src/components/@shared/button/PrimaryButton.tsx
  src/components/@shared/button/SecondaryButton.tsx
  src/components/@shared/button/TertiaryButton.tsx
  src/components/mypage/Activity.tsx
  src/components/mypage/ActivityDetail.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ThemeCard.tsx
  src/components/mypage/ThemeCardList.tsx
  src/dtos/ArticleCommentDto.ts
  src/dtos/ArticleDto.ts
  src/dtos/AuthDto.ts
  src/dtos/CategoryDto.ts
  src/dtos/FollowDto.ts
  src/dtos/ImageDto.ts
  src/dtos/OauthDto.ts
  src/dtos/ProductDto.ts
  src/dtos/ReviewDto.ts
  src/dtos/UserDto.ts
  src/libs/axios/config/path.ts
  src/pages/mypage/index.tsx
  src/pages/product/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: design

#59 Feat(나윤주): 회원가입 페이지
  README.md
  package-lock.json
  package.json
  public/icons/icon_eyes_hidden.svg
  public/icons/icon_eyes_show.svg
  public/icons/icon_google.svg
  public/icons/icon_kakao.svg
  public/images/logo.svg
  src/components/@shared/button/PrimaryButton.tsx
  src/contexts/AuthProvider.tsx
  src/dtos/AuthDto.ts
  src/dtos/OauthDto.ts
  src/hooks/(삭제)깃 인식용
  src/libs/axios/auth/auth.tsx
  src/libs/axios/axiosInstance.ts
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  src/utils/(삭제)깃 인식용
  src/utils/authTokenStorage.ts
  tailwind.config.ts
Labels: feat

#65 Feat(오정민): ThemeCard 컴포넌트를 공용 폴더로 이동
  package-lock.json
  package.json
  public/icons/(삭제)깃 인식용
  public/icons/comment_icon.svg
  public/icons/heart_icon.svg
  public/icons/star_icon.svg
  public/images/(삭제)깃 인식용
  public/images/profile_image.png
  public/images/temp1_image.png
  public/images/temp2_image.png
  public/images/temp3_image.png
  src/components/@shared/(삭제)깃 인식용
  src/components/@shared/themeCard/ThemeCard.tsx
  src/components/mypage/(삭제)깃 인식용
  src/components/mypage/Activity.tsx
  src/components/mypage/ActivityDetail.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ThemeCardList.tsx
  src/dtos/ProductDto.ts
  src/dtos/UserDto.ts
  src/libs/axios/config/path.ts
  src/pages/mypage/index.tsx
Labels: feat

#58 Feat(김세환): Product페이지 구현
  src/components/product/(삭제)깃 인식용
  src/components/product/ProductCard.tsx
  src/components/product/ProductList.tsx
  src/components/product/ProductMain.tsx
  src/components/product/ReviewerRanking.tsx
  src/components/product/Sidebar.tsx
  src/dtos/CategoryDto.ts
  src/dtos/ProductDto.ts
  src/libs/axios/instance.ts
  src/libs/axios/product/category.ts
  src/pages/product/index.tsx
  src/styles/globals.css
Labels: feat, design

#70 Retactor(김세환): 공용버튼 컴포넌트 수정
  src/components/@shared/button/CustomButton.tsx
  src/components/@shared/button/PrimaryButton.tsx
  src/components/@shared/button/SecondaryButton.tsx
  src/components/@shared/button/TertiaryButton.tsx
  src/components/mypage/Activity.tsx
  src/components/mypage/Profile.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: design

#75 Feat(김종화): 자유게시판 정렬, 검색, 게시판 조회, 페이지 네이션 구현 및 주석 추가
  next.config.js
  package-lock.json
  package.json
  src/components/@shared/DropDown.tsx
  src/components/addboard/ContentSection.tsx
  src/components/addboard/HeaderSection.tsx
  src/components/board/BestBoardCard.tsx
  src/components/board/BestBoardSection.tsx
  src/components/board/BoardCard.tsx
  src/components/board/BoardPaginationButton.tsx
  src/components/board/BoardSection.tsx
  src/components/board/BoardStatusScreen.tsx
  src/components/board/CommentCard.tsx
  src/components/board/DetailContentSection.tsx
  src/components/board/PaginationSection.tsx
  src/components/board/SearchSection.tsx
  src/dtos/ArticleDto.ts
  src/libs/axios/addboard/(삭제)깃 인식용
  src/libs/axios/addboard/postArticles.ts
  src/libs/axios/board/(삭제)깃 인식용
  src/libs/axios/board/getArticleDetail.ts
  src/libs/axios/board/getArticleDetailComments.ts
  src/libs/axios/board/getArticles.ts
  src/libs/axios/board/getArticlesByLike.ts
  src/pages/addboard/index.tsx
  src/pages/board/[id].tsx
  src/pages/board/index.tsx
Labels: feat

#97 Fix(나윤주): dev 머지 충돌 관련 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .prettierrc.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/icons/icon_glass.svg
  public/icons/icon_hamburger.svg
  public/images/logo_big_image.png
  public/images/logo_small_image.png
  src/components/@shared/button/CustomButton.tsx
  src/components/@shared/button/PrimaryButton.tsx
  src/components/@shared/button/SecondaryButton.tsx
  src/components/@shared/button/TertiaryButton.tsx
  src/components/@shared/layout/Header.tsx
  src/components/@shared/themeCard/ThemeCard.tsx
  src/components/auth/NicknamePage.tsx
  src/components/mypage/Activity.tsx
  src/components/mypage/ActivityDetail.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ThemeCardList.tsx
  src/components/product/(삭제)깃 인식용
  src/components/product/ProductCard.tsx
  src/components/product/ProductList.tsx
  src/components/product/ProductMain.tsx
  src/components/product/ReviewerRanking.tsx
  src/components/product/Sidebar.tsx
  src/dtos/CategoryDto.ts
  src/dtos/ProductDto.ts
  src/dtos/UserDto.ts
  src/libs/axios/config/path.ts
  src/libs/axios/instance.ts
  src/libs/axios/product/category.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/addboard/index.tsx
  src/pages/board/[id].tsx
  src/pages/board/index.tsx
  src/pages/mypage/index.tsx
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
  src/pages/product/[id].tsx
  src/pages/product/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/pages/user/[id].tsx
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: fix

#96 Refactor(김세환): 공용 버튼컴포넌트 리팩토링
  package-lock.json
  package.json
  src/components/@shared/button/CustomButton.tsx
Labels: refector

#101 Feat(나윤주): oauth Kakao,Google 로그인/회원가입 (머지 충돌해결)
  src/components/auth/GoogleOauthButton.tsx
  src/components/auth/KakoOauthButton.tsx
  src/components/auth/NicknamePage.tsx
  src/components/oauth/(삭제)깃 인식용
  src/components/signin/(삭제)깃 인식용
  src/components/signup/(삭제)깃 인식용
  src/contexts/AuthProvider.tsx
  src/dtos/AuthDto.ts
  src/libs/axios/auth/auth.tsx
  src/libs/axios/axiosInstance.ts
  src/libs/axios/oauth/(삭제)깃 인식용
  src/libs/axios/oauth/oAuthApps.ts
  src/libs/axios/oauth/oAuthSignIn.ts
  src/libs/axios/oauth/oAuthSignUp.ts
  src/libs/axios/signin/(삭제)깃 인식용
  src/libs/axios/signup/(삭제)깃 인식용
  src/libs/axios/user/(삭제)깃 인식용
  src/libs/axios/user/getUser.ts
  src/pages/index.tsx
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
  src/pages/oauth/signup/google.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/utils/authTokenStorage.ts
Labels: feat, fix

#84 Design(오정민): follow 관련 모달 구현 및 일부 api 연결(dev 머지)
  public/icons/close_icon.svg
  public/images/default_image.png
  src/components/@shared/modal/FollowUser.tsx
  src/components/@shared/modal/FollowUserList.tsx
  src/components/@shared/modal/Modal.tsx
  src/components/@shared/themeCard/ThemeCard.tsx
  src/components/mypage/Activity.tsx
  src/components/mypage/ActivityCard.tsx
  src/components/mypage/ActivityCardList.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ThemeCardList.tsx
  src/contexts/ModalProvider.tsx
  src/dtos/UserDto.ts
  src/libs/axios/axiosInstance.ts
  src/libs/axios/config/path.ts
  src/libs/axios/mypage/(삭제)깃 인식용
  src/libs/axios/mypage/apis.ts
  src/libs/axios/mypage/types.ts
  src/pages/mypage/index.tsx
Labels: feat, design

#95 feat(서지훈) : EscapeDetailSection 작업
  package-lock.json
  package.json
  public/images/temp4_Image_Escape.jpg
  public/images/temp5_image_Escape.png
  src/components/productDetail/EscapeDetailSection.tsx
  src/components/productDetail/FeatureTag.tsx
  src/components/productDetail/StarRating.tsx
  src/components/productDetail/Statistics.tsx
  src/pages/index.tsx
Labels: feat, design

#93 Feat(김종화): 자유게시판 CRUD 구현 완성 & 주석 추가
  public/icons/close_icon.svg
  src/components/@shared/modal/Modal.tsx
  src/components/addboard/ContentSection.tsx
  src/components/addboard/HeaderSection.tsx
  src/components/board/BoardCard.tsx
  src/components/board/BoardDeleteModal.tsx
  src/components/board/BoardPatchModal.tsx
  src/components/board/BoardSection.tsx
  src/components/board/CommentCard.tsx
  src/components/board/CommentDeleteModal.tsx
  src/components/board/CommentPatchModal.tsx
  src/components/board/DetailCommentSection.tsx
  src/components/board/DetailContentSection.tsx
  src/components/board/DetailPostCommentSection.tsx
  src/components/board/DropDown.tsx
  src/components/board/SearchSection.tsx
  src/libs/axios/board/deleteArticles.ts
  src/libs/axios/board/deleteComments.ts
  src/libs/axios/board/patchArticles.ts
  src/libs/axios/board/patchComments.ts
  src/pages/addboard/index.tsx
  src/pages/board/[id].tsx
  src/pages/board/index.tsx
Labels: feat

#121 Feat(서지훈) : 리뷰 목록 작업
  public/images/default-image.png
  src/components/productDetail/ProductReviewList.tsx
  src/components/productDetail/SortDropdown.tsx
  src/components/productDetail/StarRating.tsx
  src/dtos/ProductDto.ts
  src/pages/index.tsx
Labels: feat, design

#113 Feat(김세환): Product페이지 데이터 랜더링 등
  next.config.mjs
  public/icons/icon_signin.svg
  src/components/@shared/button/CustomButton.tsx
  src/components/@shared/layout/Header.tsx
  src/components/@shared/layout/Layout.tsx
  src/components/@shared/themeCard/ThemeCard.tsx
  src/components/product/ProductCard.tsx
  src/components/product/ProductList.tsx
  src/components/product/ProductMain.tsx
  src/components/product/ReviewerRanking.tsx
  src/components/product/Sidebar.tsx
  src/dtos/ProductDto.ts
  src/hooks/useInfiniteProduct.tsx
  src/hooks/useInfiniteScroll.tsx
  src/hooks/useProducts.tsx
  src/hooks/useRouteHandler.tsx
  src/libs/axios/axiosInstance.ts
  src/libs/axios/product/(삭제)깃 인식용
  src/libs/axios/product/categoryApi.ts
  src/libs/axios/product/productApi.ts
  src/libs/constants/category.ts
  src/pages/_app.tsx
  src/pages/product/index.tsx
  src/styles/globals.css
Labels: feat

#120 Feat(김세환): 프로덕트페이지 리뷰어 랭킹 구현
  next.config.mjs
  src/components/@shared/layout/Header.tsx
  src/components/product/ProductList.tsx
  src/components/product/ProductMain.tsx
  src/components/product/ReviewerRanking.tsx
  src/dtos/UserDto.ts
  src/libs/axios/instance.ts
  src/libs/axios/product/categoryApi.ts
  src/libs/axios/product/reviewRankingApi.ts
  src/styles/globals.css
Labels: feat

#115 Feat(나윤주): 헤더 기능 추가 및 수정
  next.config.mjs
  public/images/user_default.svg
  src/components/@shared/layout/Header.tsx
  src/pages/index.tsx
Labels: feat, design, fix

#117 Feat(나윤주): Toaster 기능 추가
  src/components/@shared/layout/Header.tsx
  src/components/auth/GoogleOauthButton.tsx
  src/components/auth/KakoOauthButton.tsx
  src/contexts/AuthProvider.tsx
  src/contexts/ToasterProvider.tsx
  src/pages/_app.tsx
  src/pages/error/index.tsx
  src/pages/oauth/google.tsx
  src/pages/signup/index.tsx
Labels: feat

#124 Fix(김세환): 화면 안나오던 문제 수정
  src/components/@shared/layout/Header.tsx
  src/components/@shared/layout/Layout.tsx
  src/pages/_app.tsx
Labels: fix

#126 Feat(오정민): 프로필 편집 기능 구현
  next.config.mjs
  public/icons/image_icon.svg
  src/components/@shared/productCard/ProductCard.tsx
  src/components/auth/GoogleOauthButton.tsx
  src/components/auth/KakoOauthButton.tsx
  src/components/auth/NicknamePage.tsx
  src/components/mypage/ActivityCardList.tsx
  src/components/mypage/FollowUser.tsx
  src/components/mypage/FollowUserList.tsx
  src/components/mypage/ProductCardList.tsx
  src/components/mypage/Profile.tsx
  src/components/user/(삭제)깃 인식용
  src/components/user/EditProfile.tsx
  src/contexts/AuthProvider.tsx
  src/contexts/ToasterProvider.tsx
  src/dtos/AuthDto.ts
  src/dtos/ImageDto.ts
  src/dtos/ProductDto.ts
  src/dtos/UserDto.ts
  src/libs/axios/auth/auth.tsx
  src/libs/axios/config/path.ts
  src/libs/axios/mypage/apis.ts
  src/libs/axios/mypage/types.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/error/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/pages/user/[id].tsx
  src/utils/authTokenStorage.ts
Labels: feat

#123 Feat(김세환): 헤더 사이드바 구현
  src/components/@shared/layout/Header.tsx
  src/components/@shared/layout/HeaderSidebar.tsx
  src/components/product/CategoryList.tsx
  src/pages/product/index.tsx
Labels: feat

#139 fix(서지훈) : api 호출 수정
  src/components/productDetail/ReviewModal.tsx
  src/components/productDetail/detail/FavoriteButton.tsx
  src/components/productDetail/detail/ProductDetailSection.tsx
  src/components/productDetail/review/ProductReviewSection.tsx
  src/components/productDetail/review/ReviewLikeButton.tsx
  src/components/productDetail/review/SortDropdown.tsx
  src/components/productDetail/statistic/ProductStatisticsSection.tsx
  src/libs/axios/product/axiosInstance.ts
  src/libs/axios/product/productApi.ts
  src/libs/axios/product/reviewApi.ts
  src/pages/_document.tsx
  src/pages/product/[id].tsx
Labels: fix

#140 Fix(나윤주): 로그인/로그아웃 타입 에러 수정
  src/components/@shared/layout/Header.tsx
  src/components/auth/GoogleOauthButton.tsx
  src/components/auth/NicknamePage.tsx
  src/contexts/AuthProvider.tsx
  src/contexts/ToasterProvider.tsx
  src/libs/axios/addboard/postArticles.ts
  src/libs/axios/oauth/oAuthApps.ts
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: fix

#143 Feat(김세환): product페이지 아이템정렬 드랍다운 추가
  src/components/@shared/layout/Header.tsx
  src/components/@shared/ui/CustomButton.tsx
  src/components/@shared/ui/CustomDropDown.tsx
  src/components/auth/NicknamePage.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/Profile.tsx
  src/components/product/ProductMain.tsx
  src/components/productDetail/detail/ProductDetailSection.tsx
  src/hooks/useRouteHandler.tsx
  src/pages/error/index.tsx
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: feat, refector

#141 Fix(김세환): QA피드백사항 수정
  src/components/@shared/layout/Header.tsx
  src/components/@shared/layout/HeaderSidebar.tsx
  src/components/@shared/layout/Layout.tsx
  src/components/product/CategoryList.tsx
  src/hooks/useRouteHandler.tsx
  src/pages/product/index.tsx
Labels: design, fix

#144 Fix(서지훈) : ReviewModal창 수정 및 QA 수정작업
  src/components/productDetail/ReviewModal.tsx
  src/components/productDetail/detail/FavoriteButton.tsx
  src/components/productDetail/detail/ProductDetailSection.tsx
  src/components/productDetail/review/ProductReviewSection.tsx
  src/components/productDetail/review/ReviewLikeButton.tsx
  src/dtos/ReviewDto.ts
  src/libs/axios/product/productApi.ts
  src/libs/axios/product/reviewApi.ts
Labels: feat, refector, fix

#146 Fix(오정민): QA 사항 수정(1차)
  next.config.mjs
  src/components/mypage/Activity.tsx
  src/components/mypage/ActivityCardList.tsx
  src/components/mypage/ActivityDetail.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/FollowUser.tsx
  src/components/mypage/Profile.tsx
  src/pages/user/[id].tsx
Labels: feat, design, fix

#148 Fix(김세환): 에러수정
  next.config.mjs
  src/hooks/useRouteHandler.tsx
Labels: fix

#153 Fix(서지훈) : QA 2차 수정 및 eslint 1차 수정
  .eslintrc.json
  src/components/productDetail/ReviewModal.tsx
  src/components/productDetail/StarRating.tsx
  src/components/productDetail/detail/FavoriteButton.tsx
  src/components/productDetail/detail/KakaoShareButton.tsx
  src/components/productDetail/detail/ProductDetailSection.tsx
  src/components/productDetail/review/ProductReviewSection.tsx
  src/components/productDetail/review/ReviewLikeButton.tsx
  src/components/productDetail/review/SortDropdown.tsx
  src/components/productDetail/statistic/ProductStatisticsSection.tsx
  src/components/productDetail/statistic/StatisticsDetail.tsx
Labels: design, refector

#157 Fix(오정민): eslint 오류 수정
  .eslintrc.json
  package.json
  src/components/mypage/Profile.tsx
  tsconfig.json
Labels: fix

#162 fix(서지훈):주석 수정
  6
  src/pages/_app.tsx
Labels: fix
